spring.application.name=cardImporter
spring.data.mongodb.uri=mongodb://localhost:27017/yugioh_db

ygoprodeck.api.url=https://db.ygoprodeck.com/api/v7/cardinfo.php

server.error.whitelabel.enabled=false